import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Hydrate from "@/components/Hydrate";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`bg-[#D2E0FB] ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Hydrate>
          <Navbar/>
          <main className="bg-[#D2E0FB] h-screen p-16">
          {children}
          </main>
        </Hydrate>
        </body>
      </html>
    </ClerkProvider>
  );
}
